// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlE2kwykxmIGMCllwuKUEKe_KVuauHzs',
    appId: '1:788323472308:web:27e29eca3c4749f22c58e1',
    messagingSenderId: '788323472308',
    projectId: 'bff-app-ee0e8',
    authDomain: 'bff-app-ee0e8.firebaseapp.com',
    storageBucket: 'bff-app-ee0e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkaWpEfp5g33i_zXer74lXiB11JgPV2oY',
    appId: '1:788323472308:android:c14d243dc3b7d2a42c58e1',
    messagingSenderId: '788323472308',
    projectId: 'bff-app-ee0e8',
    storageBucket: 'bff-app-ee0e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnuvmN9U5CuoAm8vor02s879uOPf5bgGU',
    appId: '1:788323472308:ios:32331fe68bb5854c2c58e1',
    messagingSenderId: '788323472308',
    projectId: 'bff-app-ee0e8',
    storageBucket: 'bff-app-ee0e8.appspot.com',
    iosClientId: '788323472308-4eavjmoaiig17uufhfnhkt1it7t780ap.apps.googleusercontent.com',
    iosBundleId: 'com.raywenderlich.bff',
  );
}
