name: bff
description: Beginning FlutterFire
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+7
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/